---
# tasks file for sample_apache
- name: Ensure webserver installed
  apt:
    name: apache2      
    state: present
- name: Enable and Start webserver
  service:
    name: apache2
    state: started
    enabled: true
- name: Create index.html.j2 from template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart apache2
